# Generated by Django 2.2.2 on 2019-06-24 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='my_books',
        ),
    ]
